# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-10-04 22:56
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_post_author'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='author',
            name='karma',
        ),
        migrations.RemoveField(
            model_name='author',
            name='nickname',
        ),
        migrations.RemoveField(
            model_name='author',
            name='rating',
        ),
        migrations.RemoveField(
            model_name='post',
            name='number',
        ),
        migrations.AddField(
            model_name='author',
            name='url',
            field=models.URLField(default='', unique=True, verbose_name='Ссылка'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='post',
            name='url',
            field=models.URLField(default='', unique=True, verbose_name='Ссылка'),
            preserve_default=False,
        ),
    ]
