# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-10-05 00:37
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_remove_post_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='date',
            field=models.CharField(blank=True, max_length=100, verbose_name='Дата'),
        ),
    ]
