# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-10-05 03:43
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_post_date'),
    ]

    operations = [
        migrations.RenameField(
            model_name='author',
            old_name='url',
            new_name='link',
        ),
    ]
